### ISSUE TITLE
Would you please share your code of converting spleeter checkpoint into python saved_model.pb?

### ISSUE THREAD

**Issue by ZacheryGuan** [shoegazerstella/spleeter_saved_models#1]

**Comment by shoegazerstella** [comment]
Check [this issue](https://github.com/deezer/spleeter/issues/33#issuecomment-551408960).
As far as I remember, you just need to perform 1 inference, then the model will be saved and you can retrieve it from the specified folder.
I think the saving is happening [here](https://github.com/deezer/spleeter/blob/243b3236adaf0101b3c4ffd5ad37c2c4c731b04f/spleeter/utils/estimator.py#L75)

**Comment by ZacheryGuan** [comment]
Get it. Thanks!
